### ISSUE TITLE
請問domain module的測試要怎麼run？

### ISSUE THREAD

**Issue by CarterChen247** [bng86/ReduxTodo#1]
謝謝Andy哥提供範例！
小弟已經將專案開好，準備要run test
但是發現domain模組不能run test
再請Andy哥解答～

![](https://i.imgur.com/bVkGpzi.png)

**Comment by bng86** [comment]
到 plugin 安裝 spek framework 就可以 plugin spek 的 IDE 輔助測試
or 你跑 ./gradlew test 也可以

**Comment by CarterChen247** [comment]
謝謝！裝完Android Studio的spek framework的plugin就可以run了！
